### ISSUE TITLE
Petpet KeyList is too large. Allow up to 50 images or 5000 chars

### ISSUE THREAD

**Issue by MR-MonkeyRay** [Dituon/petpet#105]
在config中加入多repourl后,生成的key list有多次重复内容导致生成的key list长度过长

```
# PetPet.yml

repositoryUrls: 
  - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/MR-MonkeyRay/petpet/main'
  - 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/Dituon/petpet/main'
```

感觉可以排序和去重之后再输出..或者这里就是一个bug?

<details>
  <summary>报错内容与生成的key list</summary>

## 报错内容
```
net.mamoe.mirai.contact.MessageTooLargeException: message(Petpet KeyList: 

acclaim ( 喝彩 欢呼 )
addiction ( 上瘾 毒瘾发作 )
always ( 要我一直 )
anyasuki ( 阿尼亚 喜欢 )
applau...) is too large. Allow up to 50 images or 5000 chars
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessagePipelineContext.verifyLength(OutgoingMessagePipeline.kt:99)
        at net.mamoe.mirai.internal.message.protocol.impl.ForwardMessageProtocol$ForwardMessageUploader.process(ForwardMessageProtocol.kt:45)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:275)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:361)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:348)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:221)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
        at net.mamoe.mirai.contact.Group$sendMessage$1.invoke(Group.kt)
        at net.mamoe.mirai.contact.Group$sendMessage$1.invoke(Group.kt)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at me.him188.kotlin.jvm.blocking.bridge.internal.RunSuspendKt.$runSuspend$(RunSuspend.kt:18)
        at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
        at petpet-6.1.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.sendKeyList(MiraiPetpet.java:458)
        at petpet-6.1.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.responseMessage(MiraiPetpet.java:190)
        at petpet-6.1.mirai2.jar//moe.dituon.petpet.mirai.MiraiPetpet.onGroupMessage(MiraiPetpet.java:158)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

## 生成的Key list

> 备注: 下为之前调试时候输出的内容

```
Petpet KeyList: 

acclaim ( 喝彩 欢呼 )
addiction ( 上瘾 毒瘾发作 )
always ( 要我一直 )
anyasuki ( 阿尼亚 喜欢 )
applaud ( 鼓掌 )
ask ( 问问 )
bible ( 圣经 典中典 )
bite ( 啃 咬 )
bocchi ( 波奇 )
brain ( 大脑升级 妈妈生的 )
breakdown ( 惊吓 击穿 )
capoo_rub ( 咖波蹭 蹭 )
carte ( 佩可莉姆 菜单 单页 )
cast ( 丢 )
center_symmetry ( 中心对称 左上对称 )
certificate ( 喜报 )
chase_train ( 追列车 追火车 )
coupon ( 陪睡 )
cover_face ( 挡 )
crawl ( 爬 )
decent_kiss ( 抱歉 )
dinosaur ( 恐龙 小恐龙 )
distracted ( 注意力 )
divorce ( 离婚申请 离婚协议 离婚 )
dont_touch ( 不要靠近 )
door ( 开门 )
down_symmetry ( 对称 下对称 上下对称 )
eat ( 吃 )
fantasy_time ( 幻想时间 )
fencing ( 击剑  )
garbage ( 垃圾桶 垃圾 探头 )
genshin_start ( 启动 )
hammer ( 锤 )
hold_sign ( 唐可可 举牌 应援 )
interview ( 采访 )
jiujiu ( 么么 )
join ( 加入 )
karyl_point ( 指 凯露指 )
keep_away ( 远离 )
kick_ball ( 踢球 )
kirby_hammer ( 卡比锤 卡比重锤 重锤 )
kiss ( 亲 热吻 )
kita ( 喜多 展示 )
knock ( 敲 打 )
kurumi ( 胡桃 放大 )
left_down_symmetry ( 中心对称 左下对称 )
leg ( 蹭 )
like ( 永远喜欢 )
loading ( 加载 加载中 )
make_friend ( 加好友 )
marry ( 结婚 )
monad ( 唐可可 拍 单页 )
nano ( 纳米科技 )
need ( 需要 )
no_response ( 无响应 )
osu
painter ( 画 )
pat ( 拍 )
peep ( 泷奈 偷看 )
perfect ( 完美 )
petpet ( 摸 摸头 )
play ( 玩 顶 )
point_tv ( 康纳 电视 )
police ( 警察 )
potato ( 土豆 )
pound ( 捣 )
printing ( 打印 )
punch ( 打拳 )
record ( 唱片 )
remake ( 泥头车 创 重开 )
reverse ( 倒放 )
reward ( 伊蕾娜 赏金 报酬 )
right_down_symmetry ( 中心对称 右下对称 )
right_symmetry ( 对称 右对称 左右对称 )
right_up_symmetry ( 中心对称 右上对称 )
rise_dead ( 诈尸 秽土转生 )
roll ( 滚 推 )
rub ( 舔 prpr )
sad_news ( 悲报 )
safe_sense ( 安全感 )
scratch_head ( 挠头 )
screen ( 屏幕 )
show_case ( 展示 )
smash ( 砸 打碎 )
stew ( 炖 )
suck ( 吸 )
support ( 精神支柱 )
sweat ( 流汗 )
symmetry ( 对称 左对称 左右对称 )
teach ( 讲课 敲黑板 )
tear ( 撕 )
thinkwhat ( 想 )
throw ( 扔 )
thump ( 锤 )
tightly ( 黏 )
twist ( 抱 )
up_symmetry ( 对称 上对称 上下对称 )
wallpaper ( 瑞克 壁纸 )
walnutpad ( 胡桃平板 平板 )
watch_tv ( 汤姆 电视 )
worship ( 膜拜 )
yoasobi ( 群青 )
masterpiece ( 名作 )
lost_notice ( 寻狗启事 )
gluing ( 打胶 )
hold ( 举牌 应援 )
bulge ( 透镜 凸透镜 鱼眼 )
pinch ( 透镜 凹透镜 捏合 )
swirl ( 扭曲 )
acclaim ( 喝彩 欢呼 )
addiction ( 上瘾 毒瘾发作 )
always ( 要我一直 )
anyasuki ( 阿尼亚 喜欢 )
applaud ( 鼓掌 )
ask ( 问问 )
bible ( 圣经 典中典 )
bite ( 啃 咬 )
bocchi ( 波奇 )
brain ( 大脑升级 妈妈生的 )
breakdown ( 惊吓 击穿 )
capoo_rub ( 咖波蹭 蹭 )
carte ( 佩可莉姆 菜单 单页 )
cast ( 丢 )
center_symmetry ( 中心对称 左上对称 )
certificate ( 喜报 )
chase_train ( 追列车 追火车 )
coupon ( 陪睡 )
cover_face ( 挡 )
crawl ( 爬 )
decent_kiss ( 抱歉 )
dinosaur ( 恐龙 小恐龙 )
distracted ( 注意力 )
divorce ( 离婚申请 离婚协议 离婚 )
dont_touch ( 不要靠近 )
door ( 开门 )
down_symmetry ( 对称 下对称 上下对称 )
eat ( 吃 )
fantasy_time ( 幻想时间 )
fencing ( 击剑  )
garbage ( 垃圾桶 垃圾 探头 )
genshin_start ( 启动 )
hammer ( 锤 )
hold_sign ( 唐可可 举牌 应援 )
interview ( 采访 )
jiujiu ( 么么 )
join ( 加入 )
karyl_point ( 指 凯露指 )
keep_away ( 远离 )
kick_ball ( 踢球 )
kirby_hammer ( 卡比锤 卡比重锤 重锤 )
kiss ( 亲 热吻 )
kita ( 喜多 展示 )
knock ( 敲 打 )
kurumi ( 胡桃 放大 )
left_down_symmetry ( 中心对称 左下对称 )
leg ( 蹭 )
like ( 永远喜欢 )
loading ( 加载 加载中 )
make_friend ( 加好友 )
marry ( 结婚 )
monad ( 唐可可 拍 单页 )
nano ( 纳米科技 )
need ( 需要 )
no_response ( 无响应 )
osu
painter ( 画 )
pat ( 拍 )
peep ( 泷奈 偷看 )
perfect ( 完美 )
petpet ( 摸 摸头 )
play ( 玩 顶 )
point_tv ( 康纳 电视 )
police ( 警察 )
potato ( 土豆 )
pound ( 捣 )
printing ( 打印 )
punch ( 打拳 )
record ( 唱片 )
remake ( 泥头车 创 重开 )
reverse ( 倒放 )
reward ( 伊蕾娜 赏金 报酬 )
right_down_symmetry ( 中心对称 右下对称 )
right_symmetry ( 对称 右对称 左右对称 )
right_up_symmetry ( 中心对称 右上对称 )
rise_dead ( 诈尸 秽土转生 )
roll ( 滚 推 )
rub ( 舔 prpr )
sad_news ( 悲报 )
safe_sense ( 安全感 )
scratch_head ( 挠头 )
screen ( 屏幕 )
show_case ( 展示 )
smash ( 砸 打碎 )
stew ( 炖 )
suck ( 吸 )
support ( 精神支柱 )
sweat ( 流汗 )
symmetry ( 对称 左对称 左右对称 )
teach ( 讲课 敲黑板 )
tear ( 撕 )
thinkwhat ( 想 )
throw ( 扔 )
thump ( 锤 )
tightly ( 黏 )
twist ( 抱 )
up_symmetry ( 对称 上对称 上下对称 )
wallpaper ( 瑞克 壁纸 )
walnutpad ( 胡桃平板 平板 )
watch_tv ( 汤姆 电视 )
worship ( 膜拜 )
yoasobi ( 群青 )
masterpiece ( 名作 )
lost_notice ( 寻狗启事 )
gluing ( 打胶 )
hold ( 举牌 应援 )
bulge ( 透镜 凸透镜 鱼眼 )
pinch ( 透镜 凹透镜 捏合 )
swirl ( 扭曲 )
acclaim ( 喝彩 欢呼 )
addiction ( 上瘾 毒瘾发作 )
always ( 要我一直 )
anyasuki ( 阿尼亚 喜欢 )
applaud ( 鼓掌 )
ask ( 问问 )
bible ( 圣经 典中典 )
bite ( 啃 咬 )
bocchi ( 波奇 )
brain ( 大脑升级 妈妈生的 )
breakdown ( 惊吓 击穿 )
capoo_rub ( 咖波蹭 蹭 )
carte ( 佩可莉姆 菜单 单页 )
cast ( 丢 )
center_symmetry ( 中心对称 左上对称 )
certificate ( 喜报 )
chase_train ( 追列车 追火车 )
coupon ( 陪睡 )
cover_face ( 挡 )
crawl ( 爬 )
decent_kiss ( 抱歉 )
dinosaur ( 恐龙 小恐龙 )
distracted ( 注意力 )
divorce ( 离婚申请 离婚协议 离婚 )
dont_touch ( 不要靠近 )
door ( 开门 )
down_symmetry ( 对称 下对称 上下对称 )
eat ( 吃 )
fantasy_time ( 幻想时间 )
fencing ( 击剑  )
garbage ( 垃圾桶 垃圾 探头 )
genshin_start ( 启动 )
hammer ( 锤 )
hold_sign ( 唐可可 举牌 应援 )
interview ( 采访 )
jiujiu ( 么么 )
join ( 加入 )
karyl_point ( 指 凯露指 )
keep_away ( 远离 )
kick_ball ( 踢球 )
kirby_hammer ( 卡比锤 卡比重锤 重锤 )
kiss ( 亲 热吻 )
kita ( 喜多 展示 )
knock ( 敲 打 )
kurumi ( 胡桃 放大 )
left_down_symmetry ( 中心对称 左下对称 )
leg ( 蹭 )
like ( 永远喜欢 )
loading ( 加载 加载中 )
make_friend ( 加好友 )
marry ( 结婚 )
monad ( 唐可可 拍 单页 )
nano ( 纳米科技 )
need ( 需要 )
no_response ( 无响应 )
osu
painter ( 画 )
pat ( 拍 )
peep ( 泷奈 偷看 )
perfect ( 完美 )
petpet ( 摸 摸头 )
play ( 玩 顶 )
point_tv ( 康纳 电视 )
police ( 警察 )
potato ( 土豆 )
pound ( 捣 )
printing ( 打印 )
punch ( 打拳 )
record ( 唱片 )
remake ( 泥头车 创 重开 )
reverse ( 倒放 )
reward ( 伊蕾娜 赏金 报酬 )
right_down_symmetry ( 中心对称 右下对称 )
right_symmetry ( 对称 右对称 左右对称 )
right_up_symmetry ( 中心对称 右上对称 )
rise_dead ( 诈尸 秽土转生 )
roll ( 滚 推 )
rub ( 舔 prpr )
sad_news ( 悲报 )
safe_sense ( 安全感 )
scratch_head ( 挠头 )
screen ( 屏幕 )
show_case ( 展示 )
smash ( 砸 打碎 )
stew ( 炖 )
suck ( 吸 )
support ( 精神支柱 )
sweat ( 流汗 )
symmetry ( 对称 左对称 左右对称 )
teach ( 讲课 敲黑板 )
tear ( 撕 )
thinkwhat ( 想 )
throw ( 扔 )
thump ( 锤 )
tightly ( 黏 )
twist ( 抱 )
up_symmetry ( 对称 上对称 上下对称 )
wallpaper ( 瑞克 壁纸 )
walnutpad ( 胡桃平板 平板 )
watch_tv ( 汤姆 电视 )
worship ( 膜拜 )
yoasobi ( 群青 )
masterpiece ( 名作 )
lost_notice ( 寻狗启事 )
gluing ( 打胶 )
hold ( 举牌 应援 )
bulge ( 透镜 凸透镜 鱼眼 )
pinch ( 透镜 凹透镜 捏合 )
swirl ( 扭曲 )
acclaim ( 喝彩 欢呼 )
addiction ( 上瘾 毒瘾发作 )
always ( 要我一直 )
anyasuki ( 阿尼亚 喜欢 )
applaud ( 鼓掌 )
ask ( 问问 )
bible ( 圣经 典中典 )
bite ( 啃 咬 )
bocchi ( 波奇 )
brain ( 大脑升级 妈妈生的 )
breakdown ( 惊吓 击穿 )
capoo_rub ( 咖波蹭 蹭 )
carte ( 佩可莉姆 菜单 单页 )
cast ( 丢 )
center_symmetry ( 中心对称 左上对称 )
certificate ( 喜报 )
chase_train ( 追列车 追火车 )
coupon ( 陪睡 )
cover_face ( 挡 )
crawl ( 爬 )
decent_kiss ( 抱歉 )
dinosaur ( 恐龙 小恐龙 )
distracted ( 注意力 )
divorce ( 离婚申请 离婚协议 离婚 )
dont_touch ( 不要靠近 )
door ( 开门 )
down_symmetry ( 对称 下对称 上下对称 )
eat ( 吃 )
fantasy_time ( 幻想时间 )
fencing ( 击剑  )
garbage ( 垃圾桶 垃圾 探头 )
genshin_start ( 启动 )
hammer ( 锤 )
hold_sign ( 唐可可 举牌 应援 )
interview ( 采访 )
jiujiu ( 么么 )
join ( 加入 )
karyl_point ( 指 凯露指 )
keep_away ( 远离 )
kick_ball ( 踢球 )
kirby_hammer ( 卡比锤 卡比重锤 重锤 )
kiss ( 亲 热吻 )
kita ( 喜多 展示 )
knock ( 敲 打 )
kurumi ( 胡桃 放大 )
left_down_symmetry ( 中心对称 左下对称 )
leg ( 蹭 )
like ( 永远喜欢 )
loading ( 加载 加载中 )
make_friend ( 加好友 )
marry ( 结婚 )
monad ( 唐可可 拍 单页 )
nano ( 纳米科技 )
need ( 需要 )
no_response ( 无响应 )
osu
painter ( 画 )
pat ( 拍 )
peep ( 泷奈 偷看 )
perfect ( 完美 )
petpet ( 摸 摸头 )
play ( 玩 顶 )
point_tv ( 康纳 电视 )
police ( 警察 )
potato ( 土豆 )
pound ( 捣 )
printing ( 打印 )
punch ( 打拳 )
record ( 唱片 )
remake ( 泥头车 创 重开 )
reverse ( 倒放 )
reward ( 伊蕾娜 赏金 报酬 )
right_down_symmetry ( 中心对称 右下对称 )
right_symmetry ( 对称 右对称 左右对称 )
right_up_symmetry ( 中心对称 右上对称 )
rise_dead ( 诈尸 秽土转生 )
roll ( 滚 推 )
rub ( 舔 prpr )
sad_news ( 悲报 )
safe_sense ( 安全感 )
scratch_head ( 挠头 )
screen ( 屏幕 )
show_case ( 展示 )
smash ( 砸 打碎 )
stew ( 炖 )
suck ( 吸 )
support ( 精神支柱 )
sweat ( 流汗 )
symmetry ( 对称 左对称 左右对称 )
teach ( 讲课 敲黑板 )
tear ( 撕 )
thinkwhat ( 想 )
throw ( 扔 )
thump ( 锤 )
tightly ( 黏 )
twist ( 抱 )
up_symmetry ( 对称 上对称 上下对称 )
wallpaper ( 瑞克 壁纸 )
walnutpad ( 胡桃平板 平板 )
watch_tv ( 汤姆 电视 )
worship ( 膜拜 )
yoasobi ( 群青 )
masterpiece ( 名作 )
lost_notice ( 寻狗启事 )
gluing ( 打胶 )
hold ( 举牌 应援 )
bulge ( 透镜 凸透镜 鱼眼 )
pinch ( 透镜 凹透镜 捏合 )
swirl ( 扭曲 )
acclaim ( 喝彩 欢呼 )
addiction ( 上瘾 毒瘾发作 )
always ( 要我一直 )
anyasuki ( 阿尼亚 喜欢 )
applaud ( 鼓掌 )
ask ( 问问 )
bible ( 圣经 典中典 )
bite ( 啃 咬 )
bocchi ( 波奇 )
brain ( 大脑升级 妈妈生的 )
breakdown ( 惊吓 击穿 )
capoo_rub ( 咖波蹭 蹭 )
carte ( 佩可莉姆 菜单 单页 )
cast ( 丢 )
center_symmetry ( 中心对称 左上对称 )
certificate ( 喜报 )
chase_train ( 追列车 追火车 )
coupon ( 陪睡 )
cover_face ( 挡 )
crawl ( 爬 )
decent_kiss ( 抱歉 )
dinosaur ( 恐龙 小恐龙 )
distracted ( 注意力 )
divorce ( 离婚申请 离婚协议 离婚 )
dont_touch ( 不要靠近 )
door ( 开门 )
down_symmetry ( 对称 下对称 上下对称 )
eat ( 吃 )
fantasy_time ( 幻想时间 )
fencing ( 击剑  )
garbage ( 垃圾桶 垃圾 探头 )
genshin_start ( 启动 )
hammer ( 锤 )
hold_sign ( 唐可可 举牌 应援 )
interview ( 采访 )
jiujiu ( 么么 )
join ( 加入 )
karyl_point ( 指 凯露指 )
keep_away ( 远离 )
kick_ball ( 踢球 )
kirby_hammer ( 卡比锤 卡比重锤 重锤 )
kiss ( 亲 热吻 )
kita ( 喜多 展示 )
knock ( 敲 打 )
kurumi ( 胡桃 放大 )
left_down_symmetry ( 中心对称 左下对称 )
leg ( 蹭 )
like ( 永远喜欢 )
loading ( 加载 加载中 )
make_friend ( 加好友 )
marry ( 结婚 )
monad ( 唐可可 拍 单页 )
nano ( 纳米科技 )
need ( 需要 )
no_response ( 无响应 )
osu
painter ( 画 )
pat ( 拍 )
peep ( 泷奈 偷看 )
perfect ( 完美 )
petpet ( 摸 摸头 )
play ( 玩 顶 )
point_tv ( 康纳 电视 )
police ( 警察 )
potato ( 土豆 )
pound ( 捣 )
printing ( 打印 )
punch ( 打拳 )
record ( 唱片 )
remake ( 泥头车 创 重开 )
reverse ( 倒放 )
reward ( 伊蕾娜 赏金 报酬 )
right_down_symmetry ( 中心对称 右下对称 )
right_symmetry ( 对称 右对称 左右对称 )
right_up_symmetry ( 中心对称 右上对称 )
rise_dead ( 诈尸 秽土转生 )
roll ( 滚 推 )
rub ( 舔 prpr )
sad_news ( 悲报 )
safe_sense ( 安全感 )
scratch_head ( 挠头 )
screen ( 屏幕 )
show_case ( 展示 )
smash ( 砸 打碎 )
stew ( 炖 )
suck ( 吸 )
support ( 精神支柱 )
sweat ( 流汗 )
symmetry ( 对称 左对称 左右对称 )
teach ( 讲课 敲黑板 )
tear ( 撕 )
thinkwhat ( 想 )
throw ( 扔 )
thump ( 锤 )
tightly ( 黏 )
twist ( 抱 )
up_symmetry ( 对称 上对称 上下对称 )
wallpaper ( 瑞克 壁纸 )
walnutpad ( 胡桃平板 平板 )
watch_tv ( 汤姆 电视 )
worship ( 膜拜 )
yoasobi ( 群青 )
masterpiece ( 名作 )
lost_notice ( 寻狗启事 )
gluing ( 打胶 )
hold ( 举牌 应援 )
bulge ( 透镜 凸透镜 鱼眼 )
pinch ( 透镜 凹透镜 捏合 )
swirl ( 扭曲 )
eat_earth ( 啃地球 )
```
</details>

**Comment by Dituon** [comment]
https://github.com/Dituon/petpet/releases/tag/6.2
