### ISSUE TITLE
无法连接到远程资源

### ISSUE THREAD

**Issue by Algar233** [Dituon/petpet#64]
貌似是更新4.9后才出现的，挂梯子也不行，资源链接能正常打开
2022-10-13 16:45:04 I/stdout: 无法连接到远程资源: https://raw.githubusercontent.com/Dituon/petpet/main/index.json
2022-10-13 16:45:04 W/stderr: Exception in thread "Thread-12" java.lang.NullPointerException
2022-10-13 16:45:04 W/stderr:   at java.base/java.util.Objects.requireNonNull(Objects.java:208)
2022-10-13 16:45:04 W/stderr:   at petpet-4.9.mirai2.jar//xmmt.dituon.plugin.DataUpdater.checkUpdate(DataUpdater.java:63)
2022-10-13 16:45:04 W/stderr:   at petpet-4.9.mirai2.jar//xmmt.dituon.plugin.DataUpdater.autoUpdate(DataUpdater.java:21)
2022-10-13 16:45:04 W/stderr:   at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Dituon** [comment]
尝试更改为国内镜像
`https://ghproxy.com/https://raw.githubusercontent.com/Dituon/petpet/main`
